---
title: "Mini-Project 2"
author: "Jessica Keast, Zainab Rizvi, Rachel LaFlamme"
date: "March 24, 2017"
output: html_document
---


## Loading the data

```{r, include=FALSE}
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

```{r}
library(tidyverse)
library(ggplot2)
```

```{r}
new_house <- house_elections %>%
  select(party, primary_votes, general_votes, state, ge_winner) %>%
  filter(party == "R" | party == "D")
  
filterVotes(field1 = "primary_votes", field2 = "general_votes")

filterVotes <- function(field1, field2) {
  new_house %>% 
   filter( field1 > 0, !is.na(field1)  & field2 > 0, !is.na(field2))
}

finalData <- new_house %>%
  mutate(diff = general_votes - primary_votes) %>%
  arrange(desc(diff)) %>%
  top_n(100)

ggplot(finalData, aes(x = primary_votes, y = general_votes)) + geom_point(aes(color = party)) + scale_color_manual(values = c("blue", "red"))
```

```{r}
new_contributions <- contributions %>%
  select(cmte_id, city, name, state, transaction_amt, transaction_pgi, cand_id, zip_code) %>%
  filter(transaction_pgi == "P") %>%
  arrange(desc(transaction_amt))

```

```{r}
state_table <- new_candidates %>%
  inner_join(new_contributions, by = c("cand_id" = "cand_id")) 
```
